---
title: "Eviction Rates in Brooklyn Over Time by Neighborhood"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(readxl)
library(tidyverse)
library(plotly)
library(tidyverse)
library(readxl)
library(plotly)
library(rgdal)
library(maps)
library(devtools)
library(leaflet)
library(maptools)
library(BAMMtools)
library(patchwork)
```



```{r spaghetti data prep, include=FALSE}

neighborhood_df = 
  read_excel("./data/NYC_neighborhoods_by_censustract_2010.xlsx", 
             skip = 5, 
             col_names = c("borough", "county_code", "boro_code", "census_tract", "PUMA", "nta_code", "neighborhood")
             ) %>% 
#creating 11 digit FIPS code by pasting country code (36) with `county_code` and `census_tract`
  mutate(geo_id = paste0("36", county_code, census_tract)
  )

brooklyn_data = read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  mutate(geoid = as.character(geoid)) %>% 
  filter(parent_location == "Kings County, New York") %>% 
  left_join(neighborhood_df, by = c("geoid" = "geo_id"))

brooklyn_data = brooklyn_data %>% 
  group_by(neighborhood, year) %>% 
  mutate(
    neighb_pop = sum(population),
    tract_weight = population/neighb_pop,
    eviction_discrepancy = eviction_filing_rate - eviction_rate,
    weighted_eviction_discrep = eviction_discrepancy*tract_weight,
    weighted_eviction_rate = eviction_rate*tract_weight,
    pct_nonwhite = 100 - pct_white,
    weighted_pct_nonwhite = pct_nonwhite*tract_weight,
    weighted_povertyrate = poverty_rate*tract_weight)
 


brooklyn_data = brooklyn_data %>% 
  summarize(
    Eviction_Rate = as.numeric(sum(weighted_eviction_rate)),
    wt_eviction_rate_discrep = sum(weighted_eviction_discrep),
    wt_pct_nonwhite = sum(weighted_pct_nonwhite),
    wt_povertyrate = sum(weighted_povertyrate)) %>% 
  ungroup() %>% 
  mutate(neighborhood = as.factor(neighborhood))

brooklyn_data <- within(brooklyn_data, Eviction_Rate[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)
brooklyn_data <- within(brooklyn_data, wt_eviction_rate_discrep[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)

```

Interactivity {.sidebar}
-----------------------------------------------------------------------

```{r}
neighborhoods = brooklyn_data %>% distinct(neighborhood) %>% pull()



# Checkbox input

checkboxGroupInput("neighborhood_choice", label=h3("Select Neighborhood"),
choices = neighborhoods, selected = "Williamsburg")


```


Figure 1 {data-width=350}
-----------------------------------------------------------------------
### Figure 1


```{r echo=FALSE}


renderPlotly({ 

brooklyn_data = 
  brooklyn_data %>%
    filter(
      neighborhood == input[["neighborhood_choice"]]
    ) 

brooklyn_data %>% 
    group_by(year) %>%
    ungroup() %>% 
    plot_ly(x=~year, y=~Eviction_Rate, type="scatter", mode="lines+markers", color = ~neighborhood) %>% 
    layout(title="Eviction Rate (%) Over Time (2000-2016) by Brooklyn Neighborhood")

})
  

```


```{r echo=FALSE}

eviction = 
  read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  filter(parent_location %in% c("New York County, New York", "Queens County, New York", "Kings County, New York", "Bronx County, New York", "Richmond County, New York"),
         population != 0) %>% 
  
  ## selecting and renaming variables
  mutate(pct_nonwhite = (100 - pct_white),
         geoid = as.character(geoid),
         year = as.ordered(year)) %>% 
  select(geoid, year, ## contextual
         evictions, eviction_filings, eviction_rate, eviction_filing_rate, renter_occupied_households, ## outcomes
         pct_nonwhite_evictiondata = pct_nonwhite, ## hypothesized predictors
         poverty_rate, rent_burden, pct_af_am, pct_renter_occupied, median_gross_rent, median_household_income, median_property_value) %>% ## other predictors
  filter(renter_occupied_households > 10) # census tracts with few renter households were creating eviction rates of 150, 200, etc.

## note: eviction filing rate calculated (# evictions / # renter occupied households)


```


```{r echo=FALSE}
## creating key for geoid <--> boro
geoid_boro_key = 
  read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  filter(parent_location %in% c("New York County, New York", "Queens County, New York", "Kings County, New York", "Bronx County, New York", "Richmond County, New York"),
         year %in% c(2010:2016)) %>% 
  select(geoid, county = parent_location) %>% 
  mutate(geoid = as.character(geoid),
         boro = recode(county, "New York County, New York" = "Manhattan", 
                               "Queens County, New York" = "Queens", 
                               "Kings County, New York" = "Brooklyn", 
                               "Bronx County, New York" = "Bronx", 
                               "Richmond County, New York" = "Staten Island")) %>% 
  distinct()
```


```{r echo=FALSE}
joined_data = 
  eviction %>% 
  inner_join(., geoid_boro_key, by = "geoid") 

## just brooklyn
joined_data_bklyn =
  joined_data %>% 
  filter(boro == "Brooklyn")

## all rows with all needed information, no missing
joined_data_bklyn_nomissing =
  joined_data_bklyn %>% 
  drop_na()
 
```





