---
title: "Meeting notes and progress tracking"
author: "Gloria Hu (gh2518)"
date: "11/20/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 11202019 Project Rescope and Assignments

### Project Rescope
- 2010-2016
- Restrict boroughs to Brooklyn
- Predictors: % English speaking, rent burden, % non-White, population density

### Questions
Question 1: How have eviction rates changed over time by census tract in Brooklyn, 2010-2016?

* Spaghetti plot of eviction rates over time (by neighborhood; if not enough data, then grouped bar chart of eviction rates (for Brooklyn overall)

* Map of eviction rates by census tract over time (choropleth)

Question 2: Are there discrepancies between eviction filing rates and eviction rates at the neighborhood level in Brooklyn?

* Stacked bar chart (or line graph) of discrepancy between eviction filing rates and eviction rates

* Map of discrepancy between eviction filing rates and eviction rates (absolute difference- percentage points)

Question 3: What factors are associated with eviction rates across census tract in Brooklyn?

* Dynamic maps of each predictor over eviction rates over time

* Simple univariate regressions of each predictor on eviction rates

### Assignments (Tuesday Nov 26)
Will
* Put all data into one file (restrict to 2010-2016, restrict all datasets to NYC counties, then join all datasets by GEOID)
* Question 3
* Website (two weeks from now)

Frances
* Create weighted neighborhood variables based on EvictionLab data
* Question 2

Naama
* Question 1
* Introduction to website (two weeks from now)

Gloria
* Question 3
* Website (two weeks from now)

## 11262019 Check-in meeting
Workflow
* Move files to website as ready- new repo

### Assignments (Sunday 1 December)
Will
* Question 3- regressions model building & Shiny, website

Frances
* Question 2- almost done, make website page

Naama
* Question 1- building shiny plotly with checkboxes, shiny slider ()

Gloria
* Question 3- make four maps based on one year of data (2016), pending regression results

### Info on GEOIDs

[Census Bureau](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html) - scroll almost all the way to the bottom
