---
title: "plots"
author: "Naama Kipperman"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(readxl)
```

Question 1

```{r}
neighborhood_df = 
  read_excel("./data/NYC_neighborhoods_by_censustract_2010.xlsx", 
             skip = 5, 
             col_names = c("borough", "county_code", "boro_code", "census_tract", "PUMA", "nta_code", "neighborhood")
             ) %>% 
#creating 11 digit FIPS code by pasting country code (36) with `county_code` and `census_tract`
  mutate(geo_id = paste0("36", county_code, census_tract)
  )
```


```{r}

# Basic descriptive plot 

eviction_rate_by_borough =  
  read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  filter(parent_location %in% c("New York County, New York", "Queens County, New York", "Kings County, New York", "Bronx County, New York", "Richmond County, New York")) %>% 
  select(parent_location, year, eviction_rate, eviction_filing_rate) %>% 
  group_by(parent_location, year) %>% 
  drop_na(eviction_rate) %>% 
  summarize(avg_eviction = mean(eviction_rate)) %>% 
    filter(parent_location %in% c("New York County, New York", "Queens County, New York", "Kings County, New York", "Bronx County, New York", "Richmond County, New York")) %>% 
  ggplot(aes(x=year, y=avg_eviction, group=parent_location, color=parent_location)) + geom_point() + geom_line() + labs(x="Year", y="Average Borough-Wide Eviction Rate 2000-2016 ")

eviction_rate_by_borough
  
  
  
# Spaghetti plot of average eviction rate across all Brooklyn census tracts over time

brooklyn_overall_plot = 
  read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  filter(parent_location %in% c("New York County, New York", "Queens County, New York", "Kings County, New York", "Bronx County, New York", "Richmond County, New York")) %>% 
  filter(parent_location=="Kings County, New York") %>% 
  mutate(
    year=as.factor(year)
  ) %>% 
  select(year, eviction_rate) %>% 
  group_by(year) %>% 
  summarize(
    avg_rate = mean(eviction_rate)
  ) %>% 
  ggplot(aes(x=year, y=avg_rate, group=1)) + geom_point() + geom_line() + labs(x="Year", y="Overall Borough-wide Rate of Eviction (%)")

brooklyn_overall_plot %>% 
  ggplotly()


# Attempt to create line graph over-time by neighborhood in Brooklyn

eviction_data_line_graph = read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  mutate(geoid = as.character(geoid)) %>% 
  filter(parent_location == "Kings County, New York") %>% 
  left_join(neighborhood_df, by = c("geoid" = "geo_id"))

line_graph_2 = eviction_data_line_graph %>% 
  group_by(neighborhood, year) %>% 
  mutate(
    neighb_pop = sum(population),
    tract_weight = population/neighb_pop,
    eviction_discrepancy = eviction_filing_rate - eviction_rate,
    weighted_eviction_discrep = eviction_discrepancy*tract_weight,
    weighted_eviction_rate = eviction_rate*tract_weight,
    pct_nonwhite = 100 - pct_white,
    weighted_pct_nonwhite = pct_nonwhite*tract_weight,
    weighted_povertyrate = poverty_rate*tract_weight)
 


line_graph_3 = line_graph_2 %>% 
  summarize(
    wt_eviction_rate = as.numeric(sum(weighted_eviction_rate)),
    wt_eviction_rate_discrep = sum(weighted_eviction_discrep),
    wt_pct_nonwhite = sum(weighted_pct_nonwhite),
    wt_povertyrate = sum(weighted_povertyrate)) %>% 
  ungroup() %>% 
  mutate(neighborhood = as.factor(neighborhood))

line_graph_3 <- within(line_graph_3, wt_eviction_rate[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)
line_graph_3 <- within(line_graph_3, wt_eviction_rate_discrep[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)

line_graph_3 %>% 
  group_by(neighborhood, year) %>% 
  ggplot(aes(x=year, y=wt_eviction_rate, group=neighborhood, color = neighborhood)) + geom_point() + geom_line() 

# ^^ very busy spaghetti plot - looking into ways to make it more interactive and nice



```



```{r}

# Map of eviction rates by census tract over time in Brooklyn (chloropleth)


```

