---
title: "Eviction Rates in Brooklyn Over Time"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(readxl)
library(tidyverse)
library(plotly)
library(tidyverse)
library(readxl)
library(plotly)
library(rgdal)
library(maps)
library(devtools)
library(leaflet)
library(maptools)
library(BAMMtools)
library(patchwork)
```



```{r spaghetti data prep, include=FALSE}

neighborhood_df = 
  read_excel("./data/NYC_neighborhoods_by_censustract_2010.xlsx", 
             skip = 5, 
             col_names = c("borough", "county_code", "boro_code", "census_tract", "PUMA", "nta_code", "neighborhood")
             ) %>% 
#creating 11 digit FIPS code by pasting country code (36) with `county_code` and `census_tract`
  mutate(geo_id = paste0("36", county_code, census_tract)
  )

brooklyn_data = read.csv('./data/EvictionData_NY.csv') %>% 
  janitor::clean_names() %>% 
  mutate(geoid = as.character(geoid)) %>% 
  filter(parent_location == "Kings County, New York") %>% 
  left_join(neighborhood_df, by = c("geoid" = "geo_id"))

brooklyn_data = brooklyn_data %>% 
  group_by(neighborhood, year) %>% 
  mutate(
    neighb_pop = sum(population),
    tract_weight = population/neighb_pop,
    eviction_discrepancy = eviction_filing_rate - eviction_rate,
    weighted_eviction_discrep = eviction_discrepancy*tract_weight,
    weighted_eviction_rate = eviction_rate*tract_weight,
    pct_nonwhite = 100 - pct_white,
    weighted_pct_nonwhite = pct_nonwhite*tract_weight,
    weighted_povertyrate = poverty_rate*tract_weight)
 


brooklyn_data = brooklyn_data %>% 
  summarize(
    Eviction_Rate = as.numeric(sum(weighted_eviction_rate)),
    wt_eviction_rate_discrep = sum(weighted_eviction_discrep),
    wt_pct_nonwhite = sum(weighted_pct_nonwhite),
    wt_povertyrate = sum(weighted_povertyrate)) %>% 
  ungroup() %>% 
  mutate(neighborhood = as.factor(neighborhood))

brooklyn_data <- within(brooklyn_data, Eviction_Rate[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)
brooklyn_data <- within(brooklyn_data, wt_eviction_rate_discrep[neighborhood == 'park-cemetery-etc-Brooklyn'] <- NA)

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
neighborhoods = brooklyn_data %>% distinct(neighborhood) %>% pull()



# Checkbox input

checkboxGroupInput("neighborhood_choice", label=h3("Select Neighborhood"),
choices = neighborhoods, selected = "Williamsburg")


```

-----------------------------------------------------------------------




```{r echo=FALSE}


renderPlotly({ 

  brooklyn_data %>%
    filter(
      neighborhood == input[["neighborhood_choice"]]
    ) %>% 
    group_by(year) %>%
    ungroup() %>% 
    plot_ly(x=~year, y=~Eviction_Rate, type="scatter", mode="lines+markers", color = ~neighborhood) %>% 
    layout(title="Eviction Rate (%) Over Time (2000-2016) by Brooklyn Neighborhood")

})
  

```



```{r map dataprep}

# Loading in Brooklyn data
joined_data_bklyn_2010 = 
  readRDS('./data/joined_data_bklyn') %>%
  filter(year == "2010")

# Loading census tract shapefiles from NYC OpenData:
census_tracts = readOGR(dsn = "mapping_files/censustracts2010.shp", encoding = "UTF-8") 

census_tracts = 
  census_tracts[census_tracts$boro_name == "Brooklyn", ]

writeOGR(census_tracts,"./mapping_files","census_temp", driver = "ESRI Shapefile", overwrite_layer = TRUE)
census_tracts = readOGR("./mapping_files","census_temp")

# Constructing geoid for merging
census_tracts@data = 
  census_tracts@data %>% 
  mutate(
    county_code = as.character(recode(boro_code, "1" = "061", "2" = "005", "3" = "047", "4" = "081", "5" = "085")),
    ct2010 = as.character(ct2010),
    fips_11dig = paste0("36", county_code, ct2010),
    long = coordinates(spTransform(census_tracts_crs, CRS("+proj=longlat +datum=WGS84")))[,1],
    lat = coordinates(spTransform(census_tracts_crs, CRS("+proj=longlat +datum=WGS84")))[,2]
    ) %>%
  unnest(c(long, lat))

# Joining data and shapefiles
census_tracts@data = left_join(census_tracts@data, joined_data_bklyn_2010, by = c("fips_11dig" = "geoid"))
```

```{r}
census_tracts_crs = spTransform(census_tracts, CRS("+init=epsg:4326"))

# writeOGR(census_tracts_crs, './mapping_files/census_tracts_geojson', layer = 'census_tracts', driver = 'GeoJSON')
```

```{r}
#pop up label
label_popup = paste0(
  "<strong>Census tract: </strong>",
  census_tracts_crs$ctlabel,
  "<br><strong>Eviction rate: </strong>",
  census_tracts_crs$eviction_rate,
  "<br><strong> % ESL: </strong>",
  census_tracts_crs$pct_eng
)

# get jenks natural breaks
getJenksBreaks(census_tracts_crs$eviction_rate, 5)
getJenksBreaks(census_tracts_crs$pct_eng, 5)

#set bins based on natural breaks
eviction_rate_bins = c(0, 1.23, 2.51, 4.12, 7.62)
pct_eng_bins = c(0, 14.6, 29.8, 46.9, 82.5)

#set color palette
eviction_palette = colorBin('Blues', bins = eviction_rate_bins, na.color = '#d9d9d9')
eng_palette = colorBin('Reds', bins = pct_eng_bins, na.color = '#d9d9d9')
```

Map of Eviction Rates by Census Tract
```{r}
leaflet::leaflet(data = census_tracts_crs) %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addPolygons(
    fillColor = ~eviction_palette(eviction_rate),
    fillOpacity = 0.8,
    color = "BDBDC3",
    weight = 1,
    popup = label_popup,
    highlightOptions = highlightOptions(color = "black", weight = 2, bringToFront = TRUE))
```


```